services:
  backend:
    build:
      context: backend
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_PORT: 3000
      MONGO_URL: mongodb://mongo:27017/notesdb
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017

volumes:
  db-data:
