{
 "title": "Envoy Metrics",
 "time": { "from": "2022-03-22T21:54:09.098Z", "to": "2022-03-22T21:56:54.439Z" },
 "templating": {
  "list": [
   {
    "name": "envoy_cluster_name",
    "label": "Destination Service",
    "query": "label_values(envoy_cluster_version, envoy_cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_connect_timeout{envoy_cluster_name=\"upstream\"}"
    }
   ]
  },
  {
   "title": "Cluster Membership",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_membership_change{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "membership changes [1m]"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=~\"$envoy_cluster_name\"})",
     "legendFormat": "total membershiip"
    },
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=~\"$envoy_cluster_name\"})",
     "legendFormat": "outlier ejections active"
    },
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$envoy_cluster_name\"})",
     "legendFormat": "healthy members (active HC and outlier)"
    },
    {
     "expr": "sum(envoy_cluster_health_check_healthy{envoy_cluster_name=~\"$envoy_cluster_name\"})",
     "legendFormat": "healthy members (active HC only)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\",envoy_cluster_name=~\"$envoy_cluster_name\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "Success Rate %"
    }
   ]
  },
  {
   "title": "Auth Denied",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_http_ext_authz_denied {envoy_http_conn_manager_prefix=\"ingress_http\"}"
    }
   ]
  },
  {
   "title": "4xx %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\",envoy_cluster_name=~\"$envoy_cluster_name\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Upstream Request Retry Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "request retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "request retry success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "request retry overflow"
    }
   ]
  },
  {
   "title": "Egress CPS / RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "egress CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "egress RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "pending req to"
    },
    {
     "expr": "sum(rate(envoy_cluster_lb_healthy_panic{envoy_cluster_name=~\"$envoy_cluster_name\"}[1m]))",
     "legendFormat": "lb healthy panic RPS"
    }
   ]
  },
  {
   "title": "Total Connections / Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"$envoy_cluster_name\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{envoy_cluster_name=\"$envoy_cluster_name\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"$envoy_cluster_name\"})",
     "legendFormat": "pending"
    }
   ]
  }
 ]
}