services:
    frontend:
      build: ./frontend
      ports:
       - 3000:3000
      volumes:
       - ./frontend:/app
      depends_on:
       - backend
      restart: always
      networks:
        - express-network
    Backend:
      build: ./backend
      ports:
       - 3000:3000
      depends_on:
       - db
      restart: always
      networks:
       - express-network
       - db-network
    db:
      image: mongo:latest
      ports:
       - 27017:27017
      volumes:
       - ./data:/data/db
      restart: always
      networks:
       - db-network
networks:
  express-network:
  db-network:   

      