services:
    frontend:
      build:
      context: frontend
      container_name: frontend
      ports:
        - 3000:3000
      restart: unless-stopped
      networks:
        - app-network
      depends_on:
        - backend
      volumes:
        - ./frontend:/app
        - /app/node_modules
    backend:
      build:
        context: backend
        container_name: backend
        expose::
          - 3000
        restart: unless-stopped
        networks:
         - app-network
         - db
        volumes:
          - ./backend:/app
          - /app/node_modules
        depends_on:
          - db
    db:
      image: mongo:8.0
      container_name: db
      restart: always
      networks:
        - db
      ports:
          - 27017:27017
      volumes:
          - ./data:/data/db
networks:
  app-network:
    driver: bridge
  db:
    driver: bridge
volumes:
  mongo_data: 
          